# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=folk.sisby
user=sisby-folk
slug=portable-crafting
modId=portable_crafting
modName=Portable Crafting
modDescription=Use crafting stations directly from your inventory.
authors=Sisby folk
license=LGPL-3.0-or-later
# Mod Version
baseVersion=3.0.3
# Branch Metadata
branch=1.19
tagBranch=1.21
compatibleVersions=1.19.2
compatibleLoaders=fabric, quilt
