[versions]
loom = "1.2.+"
githubRelease = "2.4.1"
minotaur = "2.6.0"

mc = "1.19.4"
ql = "0.19.0"
qm = "1.19.4+build.10"
fapi = "0.83.0-1.19.4"
qfapi = "6.0.0-beta.9+0.83.0-1.19.4"

inventoryTabs = "0.9.1-1.19.4-beta"

[plugins]
loom = { id = "org.quiltmc.loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
ql = { group = "org.quiltmc", name = "quilt-loader", version.ref = "ql" }
qm = { group = "org.quiltmc", name = "quilt-mappings", version.ref = "qm" }
qfapi = { group = "org.quiltmc.quilted-fabric-api", name = "quilted-fabric-api", version.ref = "qfapi" }

inventoryTabs = { group = "maven.modrinth", name = "inventory-tabs-updated", version.ref = "inventoryTabs" }
